"""Add abstract model

Revision ID: 234d81dafc86
Revises: 63ec0571da8d
Create Date: 2022-09-28 17:25:03.620175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '234d81dafc86'
down_revision = '63ec0571da8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
