"""Change project model

Revision ID: 63ec0571da8d
Revises: cc06a252fb7f
Create Date: 2022-09-28 10:04:13.015111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63ec0571da8d'
down_revision = 'cc06a252fb7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
