"""Migration 1

Revision ID: cc06a252fb7f
Revises: df1252d7c8be
Create Date: 2022-09-27 22:00:55.540342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc06a252fb7f'
down_revision = 'df1252d7c8be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
